repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-yaml
          - id: check-json
          - id: check-ast
          - id: sort-simple-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
            args:
                - --markdown-linebreak-ext=md
          - id: check-toml
          - id: check-added-large-files

    - repo: local
      hooks:
          - id: rustfmt
            name: rustfmt
            entry: cargo
            args: [fmt, --all, --, --check]
            language: system
            types: [file]
            files: \.(rs)$
            exclude: '^(\.cargo|target)/'

          - id: cargo-clippy
            name: cargo clippy
            entry: cargo
            args: [clippy, --all, --, -D, warnings]
            language: system
            types: [file]
            files: \.(rs)$
            exclude: '^(\.cargo|target)/'

          - id: cargo-build
            name: cargo build
            entry: cargo
            args: [build, --all, --release, --target, thumbv7em-none-eabihf]
            language: system
            types: [file]
            files: \.(rs)$
            exclude: '^(\.cargo|target)/'
