repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-yaml
          - id: check-json
          - id: check-ast
          - id: sort-simple-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
            args:
                - --markdown-linebreak-ext=md
          - id: check-toml
          - id: check-added-large-files

    - repo: local
      hooks:
          - id: rustfmt
            name: rustfmt
            entry: cargo
            args: [fmt, --all, --, --check]
            pass_filenames: true
            types: [file, rust]
            language: rust

          - id: clippy
            name: clippy
            entry: cargo
            args: [clippy, --all, --, -D, warnings]
            pass_filenames: false
            types: [file, rust]
            language: rust

          - id: build
            name: build
            entry: cargo
            args: [build, --release]
            pass_filenames: false
            types: [file, rust]
            language: rust
