brace_style = "PreferSameLine"
color = "Always"
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
imports_layout = "HorizontalVertical"
max_width = 120
reorder_impl_items = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
